name: Serenity BDD Tests

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Instalar Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Instalar Node.js y http-server
        run: |
          sudo apt-get install -y npm
          npm install -g http-server

      - name: Servir archivo login.html en localhost:8080
        run: |
          nohup http-server src/test/resources/paginas -p 8080 > server.log 2>&1 &

      - name: Verificar que la página está disponible
        run: |
          sleep 3
          curl -I http://localhost:8080/login/login.html

      - name: Ejecutar pruebas con Maven
        run: mvn clean verify

      - name: Subir reporte Serenity
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: serenity-report
          path: target/site/serenity
