name: Serenity BDD Tests

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Instalar Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Instalar http-server para servir login.html
        run: |
          sudo npm install -g http-server

      - name: Iniciar servidor local con http-server
        run: |
          npx http-server src/test/resources/paginas -p 8080 &
          sleep 5

      - name: Verificar disponibilidad de login.html
        run: |
          curl -I http://localhost:8080/login.html || echo "login.html no disponible"

      - name: Ejecutar pruebas con Maven
        run: mvn clean verify

      - name: Subir reporte Serenity
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: serenity-report
          path: target/site/serenity
