name: Serenity BDD Tests

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias necesarias
        run: |
          sudo apt-get update
          sudo apt-get install -y npm wget unzip xvfb
          sudo npm install -g http-server

      - name: Iniciar servidor local de HTML
        run: |
          echo "Iniciando servidor en segundo plano..."
          http-server src/test/resources/paginas -p 8080 &> /dev/null &
          sleep 5

      - name: Verificar que login.html esté disponible
        run: |
          echo "Verificando acceso a http://localhost:8080/login.html"
          curl -I http://localhost:8080/login.html || exit 1

      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Instalar Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Ejecutar pruebas con Maven
        run: mvn clean verify -Dwebdriver.base.url=http://localhost:8080/login.html

      - name: Subir reporte Serenity
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: serenity-report
          path: target/site/serenity
