name: Serenity BDD Tests

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  run-serenity-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Instalar dependencias necesarias (Chrome y herramientas)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Instalar http-server localmente
        run: npm install http-server

      - name: Iniciar servidor con HTML local
        run: |
          npx http-server src/test/resources/paginas -p 8080 &
          sleep 3

      - name: Verificar que la página esté disponible
        run: |
          curl -I http://localhost:8080/login/login.html || {
            echo "❌ La URL no está respondiendo"
            exit 1
          }

      - name: Ejecutar pruebas con Maven
        run: mvn clean verify

      - name: Subir reporte Serenity
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: serenity-report
          path: target/site/serenity
